# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_train', models.DateTimeField(verbose_name='3D-Printer')),
                ('laser_train', models.DateTimeField(verbose_name='Laser Cutter')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(verbose_name='Log Into Lab')),
                ('logout', models.DateTimeField(verbose_name='Log Out of Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=9, null=True)),
                ('employee_num', models.CharField(max_length=20, null=True)),
                ('class_org', models.CharField(max_length=20, null=True)),
                ('dept', models.CharField(max_length=20, null=True)),
                ('class_year', models.CharField(max_length=15, null=True)),
                ('suspended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginsys.Student'),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginsys.Student'),
        ),
    ]
