# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_auto_20170721_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_dates',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Training_dates',
        ),
    ]
